---
title: "Gentrification"
author: "Janhavi Nerurkar"
date: "4/9/2019"
output: pdf_document
---

```{r setup, include=FALSE}
##load("~/JSM/Data/NY.Rda")
library(ggplot2)
library(dplyr)
```

```{r Cleaning}
##NY$mgrent <- gsub("[^0-9]", "", NY$mgrent)
#NY$mgrent <- as.numeric(NY$mgrent)

##NY$npr <- gsub("[^0-9]", "", NY$npr)
##NY$npr <-as.numeric(NY$npr)

##NY$X_24a <- gsub("[^0-9]", "", NY$X_24a)
##NY$X_24a <-as.numeric(NY$X_24a)

##NY$hhinc[NY$hhinc == 999998] <- 0

# NY$mgrent[NY$mgrent == 9998] <- 0
# NY$mgrent[NY$mgrent == 9999] <- 0
# NY$mgrent[NY$mgrent == 3037] <- 0
# NY$mgrent[NY$mgrent == 3085] <- 0
# NY$mgrent[NY$mgrent == 3820] <- 0
# NY$mgrent[NY$mgrent == 4520] <- 0
# NY$mgrent[NY$mgrent == 4648] <- 0
# NY$mgrent[NY$mgrent == 7792] <- 0
# NY$mgrent[NY$mgrent == 6967] <- 0
# NY$mgrent[NY$mgrent == 7748] <- 0
# NY$mgrent[NY$mgrent == 7292] <- 0
# NY$mgrent[NY$mgrent == 99999] <- 0

# NY$X_1c <- gsub("[^0-9]", "", NY$X_1c)
# NY$X_1c <-as.numeric(NY$X_1c)

# NY$white <- 0
# NY$white[NY$X_1f == 01] <- 1
# NY$white[NY$year %in% c(2002, 2005, 2008, 2011, 2014) & substr(NY$X_1f, 1, 2) == 10] <- 1
# NY$white[NY$X_1e != 1] <- 0

#save(NY, file = 'NY.Rda')
```

```{r Aggregation}
#Mean
avg_NY <- aggregate(NY[,c("npr", "mgrent", "hhinc", "X_24a", "X_1c", "white")], by = list(NY$year,NY$borough, NY$sba), FUN = mean, na.rm = TRUE)
colnames(avg_NY) <- c("Year", "Borough", "Sub_Borough","Avg_NPR", "Avg_Rent", "Avg_Income", "Avg_Rooms", "Avg_Age", "Pct_White")
avg_NY$Rent_Inc <- (avg_NY$Avg_Rent*12)/avg_NY$Avg_Income
avg_NY$People_Room <- avg_NY$Avg_NPR/avg_NY$Avg_Rooms

#Median
# med_NY <- aggregate(NY[,c("npr", "mgrent", "hhinc", "X_24a", "X_1c")], by = list(NY$year,NY$borough, NY$sba), FUN = median, na.rm = TRUE)
# colnames(med_NY) <- c("Year", "Borough", "Sub_Borough","Med_NPR", "Med_Rent", "Med_Income", "Med_Rooms", "Med_Age")

##save(avg_NY, file = 'avg_NY.Rda')
##save(pct_NY, file = 'pct_NY.Rda')
##save(med_NY, file = 'med_NY.Rda')
```

```{r Plots}
# ggplot(data = subset(agg_NY, agg_NY$Sub_Borough %in% c("301")), aes(x = Year, y = Avg_Income), group = 1) +
#   geom_point()
```
```{r}
# ggplot(data = subset(agg_NY, agg_NY$Borough %in% c("1")), aes(x = Year, y = Avg_Income), group = 1) +
#   geom_point()
```

```{r Gentrified Sub-Boroughs}
gentri <- c("201", "308", "302", "204", "309", "307", "203", "208", "310", "101", "401", "207", "102", "216", "209")
avg_NY$Gentrified <- 0
avg_NY$Gentrified[avg_NY$Sub_Borough %in% gentri] <- 1
##table(avg_NY$Sub_Borough, avg_NY$Gentrified)
```

```{r Percentages}
pct_NY <- mutate(avg_NY, Row = 1:n()) %>%
  group_by(Sub_Borough) %>%
  mutate(Pct_Chg_Income = Avg_Income/lag(Avg_Income) -1 ) %>%
  mutate(Pct_Chg_Rent = Avg_Rent/lag(Avg_Rent) -1 ) %>%
  mutate(Pct_Chg_White = Pct_White/lag(Pct_White) -1 ) %>%
  ungroup %>%
  select(Row, Year, Sub_Borough, Gentrified, Avg_Age, Pct_Chg_Income, Pct_Chg_Rent, Rent_Inc, Pct_White, Pct_Chg_White) %>%
  na.omit(pct_NY)
pct_NY$Pct_Chg_White <- replace(pct_NY$Pct_Chg_White, pct_NY$Pct_Chg_White==Inf, 0)
```

```{r Model 1}
#% change in Rent, % change in Income, % White, Avg Age
model_1 <- glm(Gentrified ~ Pct_Chg_Income + Pct_Chg_Rent + Pct_Chg_Income*Pct_Chg_Rent + Pct_White + Avg_Age, data = pct_NY, family = "binomial")
summary(model_1)
```

```{r Model 2}
#% change in Rent, % change in Income, % White, Avg Age
model_2 <- glm(Gentrified ~ Pct_Chg_Income + Pct_Chg_Rent + Pct_Chg_Income*Pct_Chg_Rent + Pct_Chg_White + Avg_Age, data = pct_NY, family = "binomial")
summary(model_2)
```

```{r}
##table(pct_NY$Pct_Chg_White)
```

