---
title: "Plots for Presentation"
author: "Megha Pandit"
date: "April 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(geojson)
library(geojsonio)
library(leaflet)
library(ggplot2)
library(maptools)
library(magrittr)

library(sf)
library(raster)
library(spData)
library(tmap)
library(mapview)
library(magick)

library(htmlwidgets)
library(htmltools)

library(animation)
library(png)
library(webshot)
library(plotly)
```



```{r}
ny_city <- geojson_read("C:/Users/GP/Desktop/MEGHA/SemII/JSM-ASA Challenge/JSM-project/Map/nyc_sub_borough_area.geojson", what = "sp")

load("C:/Users/GP/Desktop/MEGHA/SemII/JSM-ASA Challenge/JSM-project/Data/NY.Rda")
```



```{r}
colnames(NY)[6] <- paste0("bad")
colnames(NY)[60] <- paste0("bor_subb")

NY$subb_name <- as.numeric(as.character(NY$bor_subb))

NY$subb_name[NY$bor_subb == 101] <- "Mott Haven/Hunts Point"
NY$subb_name[NY$bor_subb == 102] <- "Morrisania/Belmont"
NY$subb_name[NY$bor_subb == 103] <- "Highbridge/South Concourse"
NY$subb_name[NY$bor_subb == 104] <- "University Heights/Fordham"
NY$subb_name[NY$bor_subb == 105] <- "Kingsbridge Heights/Mosholu"
NY$subb_name[NY$bor_subb == 106] <- "Riverdale/Kingsbridge"
NY$subb_name[NY$bor_subb == 107] <- "Soundview/Parkchester"
NY$subb_name[NY$bor_subb == 108] <- "Throgs Neck/Co-op City"
NY$subb_name[NY$bor_subb == 109] <- "Pelham Parkway"
NY$subb_name[NY$bor_subb == 110] <- "Williamsbridge/Baychester"

NY$subb_name[NY$bor_subb == 201] <- "Williamsburg/Greenpoint"
NY$subb_name[NY$bor_subb == 202] <- "Brooklyn Heights/Fort Greene"
NY$subb_name[NY$bor_subb == 203] <- "Bedford Stuyvesant"
NY$subb_name[NY$bor_subb == 204] <- "Bushwick"
NY$subb_name[NY$bor_subb == 205] <- "East New York/Starrett City"
NY$subb_name[NY$bor_subb == 206] <- "Park Slope/Carroll Gardens"
NY$subb_name[NY$bor_subb == 207] <- "Sunset Park"
NY$subb_name[NY$bor_subb == 208] <- "North Crown Heights/Prospect Heights"
NY$subb_name[NY$bor_subb == 209] <- "South Crown Heights"
NY$subb_name[NY$bor_subb == 210] <- "Bay Ridge"
NY$subb_name[NY$bor_subb == 211] <- "Bensonhurst"
NY$subb_name[NY$bor_subb == 212] <- "Borough Park"
NY$subb_name[NY$bor_subb == 213] <- "Coney Island"
NY$subb_name[NY$bor_subb == 214] <- "Flatbush"
NY$subb_name[NY$bor_subb == 215] <- "Sheepshead Bay/Gravesend"
NY$subb_name[NY$bor_subb == 216] <- "Brownsville/Ocean Hill"
NY$subb_name[NY$bor_subb == 217] <- "East Flatbush"
NY$subb_name[NY$bor_subb == 218] <- "Flatlands/Canarsie"

NY$subb_name[NY$bor_subb == 301] <- "Greenwich Village/Financial District"
NY$subb_name[NY$bor_subb == 302] <- "Lower East Side/Chinatown"
NY$subb_name[NY$bor_subb == 303] <- "Chelsea/Clinton/Midtown"
NY$subb_name[NY$bor_subb == 304] <- "Stuyvesant Town/Turtle-Bay"
NY$subb_name[NY$bor_subb == 305] <- "Upper West Side"
NY$subb_name[NY$bor_subb == 306] <- "Upper East Side"
NY$subb_name[NY$bor_subb == 307] <- "Morningside Heights/Hamilton Heights"
NY$subb_name[NY$bor_subb == 308] <- "Central Harlem"
NY$subb_name[NY$bor_subb == 309] <- "East Harlem"
NY$subb_name[NY$bor_subb == 310] <- "Washington Heights/Inwood"
  
NY$subb_name[NY$bor_subb == 401] <- "Astoria"
NY$subb_name[NY$bor_subb == 402] <- "Sunnyside/Woodside"
NY$subb_name[NY$bor_subb == 403] <- "Jackson Heights"
NY$subb_name[NY$bor_subb == 404] <- "Elmhurst/Corona"
NY$subb_name[NY$bor_subb == 405] <- "Middle Village/Ridgewood"
NY$subb_name[NY$bor_subb == 406] <- "Rego Park/Forest Hills"
NY$subb_name[NY$bor_subb == 407] <- "Flushing/Whitestone"
NY$subb_name[NY$bor_subb == 408] <- "Hillcrest/Fresh Meadows"
NY$subb_name[NY$bor_subb == 409] <- "Ozone Park/Woodhaven"
NY$subb_name[NY$bor_subb == 410] <- "South Ozone Park/Howard Beach"
NY$subb_name[NY$bor_subb == 411] <- "Bayside/Little Neck"
NY$subb_name[NY$bor_subb == 412] <- "Jamaica"
NY$subb_name[NY$bor_subb == 413] <- "Queens Village"
NY$subb_name[NY$bor_subb == 414] <- "Rockaways"

NY$subb_name[NY$bor_subb == 501] <- "North Shore"
NY$subb_name[NY$bor_subb == 502] <- "Mid-Island"
NY$subb_name[NY$bor_subb == 503] <- "South Shore"

NY$bor_name <- as.numeric(as.character(NY$borough))
NY$bor_name[NY$borough == 1] <- "Bronx"
NY$bor_name[NY$borough == 2] <- "Brooklyn"
NY$bor_name[NY$borough == 3] <- "Manhattan"
NY$bor_name[NY$borough == 4] <- "Queens"
NY$bor_name[NY$borough == 5] <- "Staten Island"

colnames(NY)[8] <- paste0("bad1")

NY$Count <- rep(1,length(NY$borough))
NY$poor_win <- ifelse(NY$bad == 1 & NY$bad1 == 1, 1, ifelse(NY$bad == 1 | NY$bad1 == 1, 1, 0))
poor_windows <- NY %>%
  filter(gen == 1 | gen == 2) %>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarise(po_win = sum(poor_win), totalwin = sum(Count))
poor_windows$perc_poorwin <- round(100*poor_windows$po_win/poor_windows$totalwin, 2)

colnames(NY)[19] <- paste0("bld")
NY$building <- ifelse(NY$bld == 1 & NY$bld == 3, 1, ifelse(NY$bld == 1 | NY$bld == 3, 1, 0))
bldg1 <- NY %>%
  filter(gen == 1 | gen == 2) %>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarise(sum_bld = sum(building), totalbld = sum(Count))
bldg1$perc_bld <- round(100*bldg1$sum_bld/bldg1$totalbld, 2)

NY$rats <- ifelse(NY$X_35a == 1, 1, 0)
rats <- NY %>%
  filter(gen == 1 | gen == 2) %>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarise(sum_rats = sum(rats), totalrats = sum(Count))
rats$perc_rats <- round(100*rats$sum_rats/rats$totalrats, 2)
  
NY$kitchen <- ifelse(NY$X_26c == 2 | NY$X_26c == 9, 1, 0)
kitchen <- NY %>%
  filter(gen == 1 | gen == 2) %>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarise(sum_kitchen = sum(kitchen), totalkit = sum(Count))
kitchen$perc_kitchen <- round(100*kitchen$sum_kitchen/kitchen$totalkit, 2)

hcdata <- full_join(poor_windows, bldg1)
hcdata1 <- full_join(hcdata, rats)
hcdata2 <- full_join(hcdata1, kitchen)

save(hcdata2, file = "hcdata.Rda")

NY$China_gen1 <- ifelse(NY$gen==1 & NY$hhbirth == 17,1,0)
NY$Mexico_gen1 <- ifelse(NY$gen == 1 & NY$hhbirth == 14,1,0)
NY$India_gen1 <- ifelse(NY$gen == 1 & NY$hhbirth == 19,1,0)

NY$China_gen2 <- ifelse(NY$gen == 2 & NY$mombirth == 17 | NY$gen == 2 & NY$dadbirth == 17, 1,0)
NY$Mexico_gen2 <- ifelse(NY$gen == 2 & NY$mombirth == 14 | NY$gen == 2 & NY$dadbirth == 14, 1,0)
NY$India_gen2 <- ifelse(NY$gen == 2 & NY$mombirth == 19 | NY$gen == 2 & NY$dadbirth == 19, 1,0)


avg_income <- NY %>%
  group_by(bor_name, year, bor_subb, subb_name, gen) %>%
  summarise(avg_inc = round(mean(hhinc),2), avg_rent = round(mean(mgrent),2), avg_npr = round(mean(npr),2), avg_room = round(mean(X_24a),2),
            avg_age = round(mean(X_1c),2), gen1_China = sum(China_gen1), gen1_Mexico = sum(Mexico_gen1),
            gen1_India = sum(India_gen1), gen2_China = sum(China_gen2), gen2_Mexico = sum(Mexico_gen2),
            gen2_India = sum(India_gen2), npr = sum(npr), rooms = sum(X_24a)) %>%
  mutate(avg_ppr = round(npr/rooms, 2), log_inc = log(avg_inc), log_rent = log(avg_rent))

sub_pop <- NY %>%
  group_by(bor_subb, year)%>%
  summarise(ncount = sum(Count))

nyc_avg <- full_join(avg_income, sub_pop)
nyc_avg$China_1 <- round(100*nyc_avg$gen1_China/nyc_avg$ncount, 2)
nyc_avg$Mexico_1 <- round(100*nyc_avg$gen1_Mexico/nyc_avg$ncount, 2)
nyc_avg$India_1 <- round(100*nyc_avg$gen1_India/nyc_avg$ncount, 2)
nyc_avg$China_2 <- round(100*nyc_avg$gen2_China/nyc_avg$ncount, 2)
nyc_avg$Mexico_2 <- round(100*nyc_avg$gen2_Mexico/nyc_avg$ncount, 2)
nyc_avg$India_2 <- round(100*nyc_avg$gen2_India/nyc_avg$ncount, 2)

nyc_avg$nChina <- nyc_avg$gen1_China + nyc_avg$gen2_China
nyc_avg$nMexico <- nyc_avg$gen1_Mexico + nyc_avg$gen2_Mexico
nyc_avg$nIndia <- nyc_avg$gen1_India + nyc_avg$gen2_India
nyc_avg$China <- nyc_avg$China_1 + nyc_avg$China_2
nyc_avg$Mexico <- nyc_avg$Mexico_1 + nyc_avg$Mexico_2
nyc_avg$India <- nyc_avg$India_1 + nyc_avg$India_2

NYC <- nyc_avg[, -c(11:16, 23:28)]

save(NYC, file = "NYC_avg.Rda")
```





```{r}
#Bad Windows - 1st Generation Immigrants

#boarded_windows <- NY %>%
  #filter(gen == 1 | gen == 2)%>%
  #group_by(borough, bor_subb, subb_name, year, gen, bad1) %>%
  #summarise(total_bowd = n())

#colnames(boarded_windows)[6] <- "bad"
#bad_win <- full_join(broken_windows, boarded_windows, by = c("borough","bor_subb", "subb_name", "year", "gen", "bad"))
#bad_win[is.na(bad_win)] <- 0

#bad_win$total_bad <- bad_win$total_brwd + bad_win$total_bowd
#bad_windows <- bad_win %>%
  #mutate(sum_bad = sum(total_bad))
#bad_windows$perc_badwin <- 100*bad_windows$total_bad/bad_windows$sum_bad


badwin_map <- merge(ny_city, poor_windows, by = "bor_subb", duplicateGeoms = TRUE)

col2 <- colorRamps::blue2red(12)


risk.bins <- c(0,5,10,15,20,25,30)
risk.pal <- colorBin(col2, bins = risk.bins, na.color = "grey")

map_badwin1 <- leaflet(badwin_map[badwin_map$year == 2008 & badwin_map$bad == 1 & badwin_map$gen == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~risk.pal(perc_badwin),smoothFactor = 0.5, color = "black", fillOpacity = 0.9,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(bor_subb, ": ", "Broken/ Boarded Up Windows: ", perc_badwin, "%"))%>%
  addLegend("topleft", pal=risk.pal, values = ~perc_badwin, opacity = 1.0, title = "% of Houses with <br> Broken/Boarded Up<br> Windows")%>%
  setView(lat =  40.730610, lng = -73.935242, zoom = 10)

map_badwin2 <- leaflet(badwin_map[badwin_map$year == 2008 & badwin_map$bad == 1 & badwin_map$gen == 2,]) %>%
  addTiles() %>% addPolygons(fillColor=~risk.pal(perc_badwin),smoothFactor = 0.5, color = "black", fillOpacity = 0.9,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(bor_subb, ": ", "Broken/ Boarded Up Windows: ", perc_badwin, "%"))%>%
  addLegend("topleft", pal=risk.pal, values = ~perc_badwin, opacity = 1.0, title = "% of Houses with <br> Broken/Boarded Up<br> Windows")%>%
  setView(lat =  40.730610, lng = -73.935242, zoom = 10)

map_badwin1
map_badwin2


ggplot(bad_windows[bad_windows$gen == 1 & bad_windows$year == 1991,])+
  aes(x = bor_subb)+
  geom_bar(aes(fill = bad), position = "fill")+
  labs(title = "1st Gen Immigrant Housing with Broken/Boarded Up Windows\n1991", x = "Sub Borough", y = "Proportion")+
  scale_fill_manual("Broken/Boarded Up Windows", values = c("orangered", "orange", "darkgreen"), labels = c("1" = "Yes",
                                                                                                   "8" = "Not Reported",
                                                                                                   "9" = "No"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 8))


ggplot(bad_windows[bad_windows$gen == 1 & bad_windows$year == 2017,])+
  aes(x = bor_subb)+
  geom_bar(aes(fill = bad), position = "fill")+
  labs(title = "1st Gen Immigrant Housing with Broken/Boarded Up Windows\n2017", x = "Sub Borough", y = "Proportion")+
  scale_fill_manual("Broken/Boarded Up Windows", values = c("orangered", "orange", "darkgreen"), labels = c("1" = "Yes",
                                                                                                   "8" = "Not Reported",
                                                                                                   "9" = "No"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 8))


ggplot(bad_windows[bad_windows$gen == 2 & bad_windows$year == 1991,])+
  aes(x = bor_subb)+
  geom_bar(aes(fill = bad), position = "fill")+
  labs(title = "2nd Gen Immigrant Housing with Broken/Boarded Up Windows\n1991", x = "Sub Borough", y = "Proportion")+
  scale_fill_manual("Broken/Boarded Up Windows", values = c("orangered", "orange", "darkgreen"), labels = c("1" = "Yes",
                                                                                                   "8" = "Not Reported",
                                                                                                   "9" = "No"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 8))

ggplot(bad_windows[bad_windows$gen == 2 & bad_windows$year == 2017,])+
  aes(x = bor_subb)+
  geom_bar(aes(fill = bad), position = "fill")+
  labs(title = "2nd Gen Immigrant Housing with Broken/Boarded Up Windows\n2017", x = "Sub Borough", y = "Proportion")+
  scale_fill_manual("Broken/Boarded Up Windows", values = c("orangered", "orange", "darkgreen"), labels = c("1" = "Yes",
                                                                                                   "8" = "Not Reported",
                                                                                                   "9" = "No"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 8))
  
```




```{r}
#Condition of Building

col <- grDevices::rainbow(12)
pal.bins <- c(0,10,15,20,30,40,50)
pal <- colorBin("RdPu", bins = pal.bins)

colnames(NY)[19] <- paste0("bld")

bld_map <- merge(ny_city, bldg1, by = "bor_subb", duplicateGeoms = TRUE)

map1 <- leaflet(bld_map[bld_map$year == 1991 & bld_map$gen == 1 & bld_map$bld == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal(perc_bld),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of Buildings in Dilapidated/Deteriorating Condition: ", perc_bld))%>%
  addLegend("topleft", pal=pal, values = ~perc_bld, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>% of Buildings<br>in Dilapidated/<br>Deteriorating Condition")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

map2 <- leaflet(bld_map[bld_map$year == 1991 & bld_map$gen == 2 & bld_map$bld == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal(perc_bld),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of Buildings in Dilapidated/Deteriorating Condition: ", perc_bld))%>%
  addLegend("topleft", pal=pal, values = ~perc_bld, opacity = 1.0, title = paste0("1991<br>2nd Gen", "<br>% of Buildings<br>in Dilapidated/<br>Deteriorating Condition")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

map3 <- leaflet(bld_map[bld_map$year == 2017 & bld_map$gen == 1 & bld_map$bld == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal(perc_bld),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of Buildings in Dilapidated/Deteriorating Condition: ", perc_bld))%>%
  addLegend("topleft", pal=pal, values = ~perc_bld, opacity = 1.0, title = paste0("2017<br>1st Gen", "<br>% of Buildings<br>in Dilapidated/<br>Deteriorating Condition")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

map4 <- leaflet(bld_map[bld_map$year == 2017 & bld_map$gen == 2 & bld_map$bld == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal(perc_bld),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of Buildings in Dilapidated/Deteriorating Condition: ", perc_bld))%>%
  addLegend("topleft", pal=pal, values = ~perc_bld, opacity = 1.0, title = paste0("2017<br>2nd Gen", "<br>% of Buildings<br>in Dilapidated/<br>Deteriorating Condition")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

```





```{r}
#Average Income, Average Rent, Average Number of Persons per Room

col_avg <- colorBin("YlGn", bins = c(8.5,9,9.5,10,10.5,11,11.5,12,12.5,13))

NY$China_gen1 <- ifelse(NY$gen==1 & NY$hhbirth == 17,1,0)
NY$Mexico_gen1 <- ifelse(NY$gen == 1 & NY$hhbirth == 14,1,0)
NY$India_gen1 <- ifelse(NY$gen == 1 & NY$hhbirth == 19,1,0)

NY$China_gen2 <- ifelse(NY$gen == 2 & NY$mombirth == 17 | NY$gen == 2 & NY$dadbirth == 17, 1,0)
NY$Mexico_gen2 <- ifelse(NY$gen == 2 & NY$mombirth == 14 | NY$gen == 2 & NY$dadbirth == 14, 1,0)
NY$India_gen2 <- ifelse(NY$gen == 2 & NY$mombirth == 19 | NY$gen == 2 & NY$dadbirth == 19, 1,0)


avg_income <- NY %>%
  filter(gen == 1 | gen == 2) %>%
  group_by(bor_name, year, bor_subb, subb_name, gen) %>%
  summarise(avg_inc = round(mean(hhinc),2), avg_rent = round(mean(mgrent),2), avg_npr = round(mean(npr),2), avg_room = round(mean(X_24a),2),
            avg_age = round(mean(X_1c),2), gen1_China = sum(China_gen1), gen1_Mexico = sum(Mexico_gen1),
            gen1_India = sum(India_gen1), gen2_China = sum(China_gen2), gen2_Mexico = sum(Mexico_gen2),
            gen2_India = sum(India_gen2), npr = sum(npr), rooms = sum(X_24a)) %>%
  mutate(avg_ppr = round(npr/rooms, 2), log_inc = log(avg_inc), log_rent = log(avg_rent))

sub_pop <- NY %>%
  group_by(bor_subb, year)%>%
  summarise(ncount = sum(Count))

nyc_avg <- left_join(avg_income, sub_pop, by = NULL)
nyc_avg$China_1 <- round(100*nyc_avg$gen1_China/nyc_avg$ncount, 2)
nyc_avg$Mexico_1 <- round(100*nyc_avg$gen1_Mexico/nyc_avg$ncount, 2)
nyc_avg$India_1 <- round(100*nyc_avg$gen1_India/nyc_avg$ncount, 2)
nyc_avg$China_2 <- round(100*nyc_avg$gen2_China/nyc_avg$ncount, 2)
nyc_avg$Mexico_2 <- round(100*nyc_avg$gen2_Mexico/nyc_avg$ncount, 2)
nyc_avg$India_2 <- round(100*nyc_avg$gen2_India/nyc_avg$ncount, 2)

nyc_avg$nChina <- nyc_avg$gen1_China + nyc_avg$gen2_China
nyc_avg$nMexico <- nyc_avg$gen1_Mexico + nyc_avg$gen2_Mexico
nyc_avg$nIndia <- nyc_avg$gen1_India + nyc_avg$gen2_India
nyc_avg$China <- nyc_avg$China_1 + nyc_avg$China_2
nyc_avg$Mexico <- nyc_avg$Mexico_1 + nyc_avg$Mexico_2
nyc_avg$India <- nyc_avg$India_1 + nyc_avg$India_2

NYC <- nyc_avg[, -c(10:15,20:25)]

save(NYC, file = "NYC_avg.Rda")
save(NYC, file = "NYC_avg.csv")

avg_map <- merge(ny_city, NYC, by = "bor_subb", duplicateGeoms = TRUE)

```




```{r}
#Maps plotted only forone year - adjust in shiny accordingly

#Average Income Map for 1st and 2nd Generation Immigrants
#Defining colors for the map
col_avg <- colorBin("YlGn", bins = c(8.5,9,9.5,10,10.5,11,11.5,12,12.5,13))

avg_inc_1 <- leaflet(avg_map[avg_map$year == 1991 & avg_map$gen == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~col_avg(log_inc),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "Average Income: $", avg_inc))%>%
  addLegend("topleft", pal=col_avg, values = ~log_inc, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>Log Average Income")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

avg_inc_2 <- leaflet(avg_map[avg_map$year == 1991 & avg_map$gen == 2,]) %>%
  addTiles() %>% addPolygons(fillColor=~col_avg(log_inc),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "Average Income: $", avg_inc))%>%
  addLegend("topleft", pal=col_avg, values = ~log_inc, opacity = 1.0, title = paste0("1991<br>2nd Gen", "<br>Log Average Income")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

avg_inc_1
avg_inc_2
```



```{r}
#Average Rent Map for 1st and 2nd Generation Immigrants
#Defining colors for the map
col_avg1 <- rev(colorspace::heat_hcl(12))
pal_avg_rent <- colorBin(col_avg1, bins = c(4,4.5,5,5.5,6,6.5,7,7.5,8))

avg_rent_1 <- leaflet(avg_map[avg_map$year == 1991 & avg_map$gen == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_avg_rent(log_rent),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "Average Rent: $", avg_rent))%>%
  addLegend("topleft", pal=pal_avg_rent, values = ~log_rent, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>Log Average Rent")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

avg_rent_2 <- leaflet(avg_map[avg_map$year == 1991 & avg_map$gen == 2,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_avg_rent(log_rent),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "Average Rent: $", avg_rent))%>%
  addLegend("topleft", pal=pal_avg_rent, values = ~log_rent, opacity = 1.0, title = paste0("1991<br>2nd Gen", "<br>Log Average Rent")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

avg_rent_1
avg_rent_2
```




```{r}
#Average number of rooms per household by sub-borough
col_room <- rev(grDevices::terrain.colors(12))
pal_room <- colorBin(col_room, bins = c(2,2.5,3,3.5,4,4.5,5,5.5,6,6.5))

avg_room_1 <- leaflet(avg_map[avg_map$year == 2017 & avg_map$gen == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_room(avg_room),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "Average Number of Rooms: ", avg_room))%>%
  addLegend("topleft", pal=pal_room, values = ~avg_room, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>Average Number of Rooms")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

avg_room_2 <- leaflet(avg_map[avg_map$year == 2017 & avg_map$gen == 2,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_room(avg_room),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "Average Number of Rooms: ", avg_room))%>%
  addLegend("topleft", pal=pal_room, values = ~avg_room, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>Average Number of Rooms")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

avg_room_1
avg_room_2

```




```{r}
#Average number of persons per room

col_ppr <- colorspace::heat_hcl(12, h = c(0,-100), l = c(75,40), c = c(40,80), power = 1)
pal_ppr <- colorBin(col_ppr, bins = c(0,0.25,0.5,0.75,1,1.25))

avg_ppr_1 <- leaflet(avg_map[avg_map$year == 2017 & avg_map$gen == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_ppr(avg_ppr),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "Average Number Persons per Rooms: ", avg_ppr))%>%
  addLegend("topleft", pal=pal_ppr, values = ~avg_ppr, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>Average Number of Persons<br>per Room")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

avg_ppr_2 <- leaflet(avg_map[avg_map$year == 2017 & avg_map$gen == 2,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_ppr(avg_ppr),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "Average Number Persons per Rooms: ", avg_ppr))%>%
  addLegend("topleft", pal=pal_ppr, values = ~avg_ppr, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>Average Number of Persons<br>per Room")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

avg_ppr_1
avg_ppr_2

```




```{r}
#Percentage of Chinese Immigrant Population - 1st and 2nd Generation Immigrants

pal_imm <- colorNumeric("viridis", NULL)

perc_china_1 <- leaflet(avg_map[avg_map$year == 2017 & avg_map$gen == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_imm(China),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of 1st Generation Chinese Immigrants: ", China))%>%
  addLegend("topleft", pal=pal_imm, values = ~China, opacity = 1.0, title = paste0("2017<br>1st Gen", "<br>% of<br>Chinese Immigrants")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

perc_china_2 <- leaflet(avg_map[avg_map$year == 2017 & avg_map$gen == 2,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_imm(China),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of 2nd Generation Chinese Immigrants: ", China))%>%
  addLegend("topleft", pal=pal_imm, values = ~China, opacity = 1.0, title = paste0("2017<br>2nd Gen", "<br>% of<br>Chinese Immigrants")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

perc_china_1
perc_china_2

```




```{r}
#Percentage of Mexican Immigrant Population - 1st and 2nd Generation Immigrants

perc_mex_1 <- leaflet(avg_map[avg_map$year == 1991 & avg_map$gen == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_imm(Mexico),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of 1st Generation Mexican Immigrants: ", Mexico))%>%
  addLegend("topleft", pal=pal_imm, values = ~Mexico, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>% of<br>Mexican Immigrants")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

perc_mex_2 <- leaflet(avg_map[avg_map$year == 1991 & avg_map$gen == 2,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_imm(Mexico),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of 2nd Generation Mexican Immigrants: ", Mexico))%>%
  addLegend("topleft", pal=pal_imm, values = ~Mexico, opacity = 1.0, title = paste0("1991<br>2nd Gen", "<br>% of<br>Mexican Immigrants")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

perc_mex_1
perc_mex_2

```




```{r}
#Percentage of Indian Immigrant Population - 1st and 2nd Generation Immigrants

perc_india_1 <- leaflet(avg_map[avg_map$year == 1991 & avg_map$gen == 1,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_imm(India),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of 1st Generation Indian Immigrants: ", India))%>%
  addLegend("topleft", pal=pal_imm, values = ~India, opacity = 1.0, title = paste0("1991<br>1st Gen", "<br>% of<br>Indian Immigrants")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

perc_india_2 <- leaflet(avg_map[avg_map$year == 2017 & avg_map$gen == 2,]) %>%
  addTiles() %>% addPolygons(fillColor=~pal_imm(India),smoothFactor = 0.5, color = "black", fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(subb_name, ": ", "% of 2nd Generation Indian Immigrants: ", India))%>%
  addLegend("topleft", pal=pal_imm, values = ~India, opacity = 1.0, title = paste0("2017<br>2nd Gen", "<br>% of<br>Indian Immigrants")) %>%
      setView(lat =  40.730610, lng = -73.935242, zoom = 10)

perc_india_1
perc_india_2
```



```{r}
# Dataset for ggplots

poor_windows1 <- NY %>%
  filter(gen == 1 | gen == 2)%>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarise(sum = sum(poor_win), ncount = sum(Count))
poor_windows1$perc <- round(100*poor_windows1$sum/poor_windows1$ncount, 2)
poor_windows1$condition <- "Broken/Boarded Up Windows"

bldg <- NY %>%
  filter(gen == 1 | gen == 2)%>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarise(sum = sum(building), ncount = sum(Count))
bldg$perc <- round(100*bldg$sum/bldg$ncount, 2)
bldg$condition <- "Poor Building Conditions"

rats1 <- NY %>%
  filter(gen == 1 | gen == 2)%>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarise(sum = sum(rats), ncount = sum(Count))
rats1$perc <- round(100*rats1$sum/rats1$ncount, 2)
rats1$condition <- "Presence of Rats"
  
kitchen1 <- NY %>%
  filter(gen == 1 | gen == 2)%>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarise(sum = sum(kitchen), ncount = sum(Count))
kitchen1$perc <- round(100*kitchen1$sum/kitchen1$ncount, 2)
kitchen1$condition <- "No/Non-functioning Kitchen"

NY$immigrant <- ifelse(NY$gen == 1 | NY$gen == 2, 1, 0)
immigrant1 <- NY %>%
  group_by(bor_name, bor_subb, subb_name, year, gen) %>%
  summarize(sum = sum(immigrant))

sub_pop <- NY %>%
  group_by(bor_subb, year)%>%
  summarise(ncount = sum(Count))
imm1 <- full_join(immigrant1, sub_pop)
imm1$perc <- round(100*imm1$sum/imm1$ncount, 2)
imm1$condition <- "Immigrants"

ggdata1 <- rbind(poor_windows1, bldg)
ggdata2 <- rbind(ggdata1, rats1)
ggdata3 <- rbind(ggdata2, kitchen1)
ggdata <- rbind(ggdata3, imm1)
ggdata <- as.data.frame(ggdata)
save(ggdata, file = "ggdata.Rda")
```




```{r}
#plotly maps for pop ups

p101<- plot_ly(data = ggdata[ggdata$year == 1991 & ggdata$gen == 1 & ggdata$bor_subb == 101,], x = ~condition, y = ~perc, type = "bar", color = ~condition)%>%
  layout(yaxis = list(title = 'Percentage of Households'))
hide_legend(p101)
```

