---
title: "Map"
author: "LonghaoChen&Megha"
date: "3/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(leaflet)
library(geojsonio)
library(readr)
library(fuzzyjoin)
library(sp)
library(tidyverse)
```


```{r}
#Input the nycity contour 
nycity <- geojsonio::geojson_read("nyc_sub_borough_area.geojson", what = "sp")

#Load 2017 data
data_2014<- read_csv("NYCHVS 2014 Occupied File for ASA Challenge_CSV.csv", skip = 1)
names(data_2014)[names(data_2014)=="`Borough and Sub-Borough Area`"] <- "bor_subb"

data_1991 <-read_csv("NYCHVS 1991 Occupied File for ASA Challenge_CSV.csv", skip = 1)
names(data_2014)[names(data_2014)=="`Borough and Sub-Borough Area`"] <- "bor_subb"

test <- data_2014 %>% select(`Borough and Sub-Borough Area`,`Monthly contract rent`) %>% rename(bor_subb=`Borough and Sub-Borough Area`)

averagerent<- test %>% filter(`Monthly contract rent`<99900) %>% group_by(bor_subb) %>% mutate(averagerent = mean(`Monthly contract rent`),medianrent=median(`Monthly contract rent`)) %>% distinct(bor_subb, .keep_all = TRUE)

#Join both tables together

test_birth <- data_2014 %>% select(`Borough and Sub-Borough Area`,`Place of Householder's Birth`) %>% rename(bor_subb=`Borough and Sub-Borough Area`)


#Merge into one table

subdata <- merge(nycity,test_birth, by = "bor_subb",duplicateGeoms = TRUE) 

#Color palette
pal <- colorNumeric("viridis", NULL)

leaflet(subdata) %>%
  addTiles() %>%
  addPolygons( fillColor=~pal(log10(averagerent)),smoothFactor = 0.5, fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(bor_subb, ": ", "Average rent  ",formatC(averagerent, big.mark = ","),"  Median rent  ", formatC(medianrent,big.mark = ","))) %>%
  addLegend(pal=pal, values = ~log10(averagerent), opacity = 1.0,
    labFormat = labelFormat(transform = function(x) round(10^x)))

#new dataframe
number_immigrant<- test_birth %>% filter(`Place of Householder's Birth` != 7 &`Place of Householder's Birth` != 9&`Place of Householder's Birth` != 98) %>% group_by(bor_subb) %>% summarize(first_generation = n()) 


#
subdata <- merge(nycity,number_immigrant, by = "bor_subb",duplicateGeoms = TRUE) 

#Second map
leaflet(subdata) %>%
  addTiles() %>%
  addPolygons( fillColor=~pal((first_generation)),smoothFactor = 0.5, fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(bor_subb, ": ", " Number of first generation immigrants ",formatC(first_generation))) %>%
  addLegend(pal=pal, values = ~(first_generation), opacity = 1.0,
    labFormat = labelFormat(transform = function(x) x))


#
number_immigrant <- data_1991 %>% select(`Borough and Sub-Borough Area`,`Place of Householder's Birth`) %>% rename(bor_subb=`Borough and Sub-Borough Area`) %>% filter(`Place of Householder's Birth` != 10 &`Place of Householder's Birth` != 98) %>% group_by(bor_subb) %>% summarize(first_generation = n()) 

#
subdata <- merge(nycity,number_immigrant, by = "bor_subb",duplicateGeoms = TRUE) 
#
leaflet(subdata) %>%
  addTiles() %>%
  addPolygons( fillColor=~pal((first_generation)),smoothFactor = 0.5, fillOpacity = 1,weight=1,highlightOptions = highlightOptions(color = "white", weight = 2.5,
      bringToFront = TRUE),label = ~paste0(bor_subb, ": ", " Number of first generation immigrants ",formatC(first_generation))) %>%
  addLegend(pal=pal, values = ~(first_generation), opacity = 1.0,
    labFormat = labelFormat(transform = function(x) x))
```



```{r}



nyc_fico$borough <- gsub('Staten', 'Staten Island', nyc_fico$borough) 
map_data_fico <- geo_join(nyc_boroughs, nyc_fico, "BoroName", "borough",how="inner") 


pal0 <- colorNumeric(palette = "YlOrRd", 
                     domain = range(map_data_fico@data$avg_fico)) 
centers0 <- data.frame(gCentroid(map_data_fico,byid=TRUE)) 
centers0$region <- row.names(map_data_fico) 
centers0$region <- ifelse(centers0$region=="0","Staten Island", 
                          ifelse(centers0$region=="1","Queens", 
                                 ifelse(centers0$region=="2","Brooklyn", 
                                        ifelse(centers0$region=="3","Manhattan", 
                                               "Bronx")))) 
leaflet(map_data_fico) %>% 
  addTiles() %>%  
  addPolygons(stroke=TRUE,weight=1,fillOpacity = 0.5, smoothFactor = 0.5, 
              color = "black",fillColor = ~pal0(avg_fico), popup = ~as.character(avg_fico)) %>% 
  addLabelOnlyMarkers(data=centers0,lng = ~x,lat = ~y, label = ~region,labelOptions = labelOptions(noHide = TRUE, direction = 'top', textOnly = TRUE)) %>% 
  addLegend("bottomright", pal = pal0, values = ~avg_fico, 
            title = "Average Fico Score", 
            opacity = 1 
  ) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  setView(-73.91, 40.70, zoom = 10)
```

